@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Fri Mar 15 15:22:44 +0000 2024
REM SW Build 2700185 on Thu Oct 24 18:46:05 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim final_design_wrapper_tb_behav -key {Behavioral:sim_1:Functional:final_design_wrapper_tb} -tclbatch final_design_wrapper_tb.tcl -protoinst "protoinst_files/final_design.protoinst" -protoinst "protoinst_files/design_1.protoinst" -view U:/EEE228/EEE228_Microprocessor/Microprocessor/final_design_wrapper_tb_behav.wcfg -log simulate.log"
call xsim  final_design_wrapper_tb_behav -key {Behavioral:sim_1:Functional:final_design_wrapper_tb} -tclbatch final_design_wrapper_tb.tcl -protoinst "protoinst_files/final_design.protoinst" -protoinst "protoinst_files/design_1.protoinst" -view U:/EEE228/EEE228_Microprocessor/Microprocessor/final_design_wrapper_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
