webtalk_init -webtalk_dir U:/EEE228/EEE228_Microprocessor/Microprocessor/Microprocessor.sim/sim_1/behav/xsim/xsim.dir/final_design_wrapper_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Mar 15 15:35:03 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2700185" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211517450_1777531306_210672901_148" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "d4271b64-9545-4607-b5fa-539772a74b74" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "53535327eabe4993b7d6989b9b237616" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "178" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3192 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.11_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7660_KB" -context "xsim\\usage"
webtalk_transmit -clientid 740416325 -regid "211517450_1777531306_210672901_148" -xml U:/EEE228/EEE228_Microprocessor/Microprocessor/Microprocessor.sim/sim_1/behav/xsim/xsim.dir/final_design_wrapper_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html U:/EEE228/EEE228_Microprocessor/Microprocessor/Microprocessor.sim/sim_1/behav/xsim/xsim.dir/final_design_wrapper_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm U:/EEE228/EEE228_Microprocessor/Microprocessor/Microprocessor.sim/sim_1/behav/xsim/xsim.dir/final_design_wrapper_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
