# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: U:/EEE228/Nexys-4-DDR-Master.xdc

# Block Designs: bd/final_design/final_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==final_design || ORIG_REF_NAME==final_design} -quiet] -quiet

# IP: bd/final_design/ip/final_design_Program_counter_0_0/final_design_Program_counter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==final_design_Program_counter_0_0 || ORIG_REF_NAME==final_design_Program_counter_0_0} -quiet] -quiet

# IP: bd/final_design/ip/final_design_ROM_0_0/final_design_ROM_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==final_design_ROM_0_0 || ORIG_REF_NAME==final_design_ROM_0_0} -quiet] -quiet

# IP: bd/final_design/ip/final_design_Instruction_Register_0_0/final_design_Instruction_Register_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==final_design_Instruction_Register_0_0 || ORIG_REF_NAME==final_design_Instruction_Register_0_0} -quiet] -quiet

# IP: bd/final_design/ip/final_design_Instruction_Decoder_0_0/final_design_Instruction_Decoder_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==final_design_Instruction_Decoder_0_0 || ORIG_REF_NAME==final_design_Instruction_Decoder_0_0} -quiet] -quiet

# IP: bd/final_design/ip/final_design_Shifter_0_0/final_design_Shifter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==final_design_Shifter_0_0 || ORIG_REF_NAME==final_design_Shifter_0_0} -quiet] -quiet

# IP: bd/final_design/ip/final_design_Register_A_0_0/final_design_Register_A_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==final_design_Register_A_0_0 || ORIG_REF_NAME==final_design_Register_A_0_0} -quiet] -quiet

# IP: bd/final_design/ip/final_design_Register_B_0_0/final_design_Register_B_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==final_design_Register_B_0_0 || ORIG_REF_NAME==final_design_Register_B_0_0} -quiet] -quiet

# IP: bd/final_design/ip/final_design_Register_O_0_0/final_design_Register_O_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==final_design_Register_O_0_0 || ORIG_REF_NAME==final_design_Register_O_0_0} -quiet] -quiet

# IP: bd/final_design/ip/final_design_MUX_0_0/final_design_MUX_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==final_design_MUX_0_0 || ORIG_REF_NAME==final_design_MUX_0_0} -quiet] -quiet

# IP: bd/final_design/ip/final_design_MUX_1_0/final_design_MUX_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==final_design_MUX_1_0 || ORIG_REF_NAME==final_design_MUX_1_0} -quiet] -quiet

# IP: bd/final_design/ip/final_design_ALU_0_0/final_design_ALU_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==final_design_ALU_0_0 || ORIG_REF_NAME==final_design_ALU_0_0} -quiet] -quiet

# IP: bd/final_design/ip/final_design_Accumulator_0_0/final_design_Accumulator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==final_design_Accumulator_0_0 || ORIG_REF_NAME==final_design_Accumulator_0_0} -quiet] -quiet

# XDC: bd/final_design/final_design_ooc.xdc
